CREATE TABLE noteful_folders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    foldername TEXT NOT NULL UNIQUE
);

CREATE TABLE noteful_inventory (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product TEXT NOT NULL,
    folderId INTEGER
        REFERENCES noteful_folders(id) ON DELETE CASCADE NOT NULL,
    quantity INTEGER NOT NULL,
    size TEXT NOT NULL
);

CREATE TABLE noteful_purchases (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    folderId INTEGER
        REFERENCES noteful_folders(id) ON DELETE CASCADE NOT NULL,
    cust_name TEXT NOT NULL,
    total FLOAT NOT NULL,
    comment TEXT NOT NULL,
    payment_status BOOLEAN DEFAULT false,
    modified TIMESTAMP DEFAULT now() NOT NULL
);