DROP TABLE IF EXISTS noteful_inventory;

CREATE TABLE noteful_inventory (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product TEXT NOT NULL,
    folderId INTEGER
        REFERENCES noteful_folders(id) ON DELETE CASCADE NOT NULL,
    quantity INTEGER NOT NULL,
    size TEXT NOT NULL
);
