DROP TABLE IF EXISTS noteful_profiles;

CREATE TABLE noteful_profiles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    folderId INTEGER
        REFERENCES noteful_folders(id) ON DELETE CASCADE NOT NULL,
    cust_name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    membership BOOLEAN DEFAULT false,
    ER BOOLEAN DEFAULT false,
    comment TEXT,
    modified TIMESTAMP DEFAULT now() NOT NULL
);